version: "3.9"
services:
  with-warp:
    build: ./with-warp
  sse-bencher:
    build: ./sse-bencher
    environment:
      - SERVER=with-warp:8080
    depends_on:
      - with-warp
    sysctls:
      - net.ipv4.ip_local_port_range=1024 60999
