[package]
name = "ws-bencher"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
futures-util = "0.3.21"
rand = "0.8.5"
tokio = { version = "1.18.2", features = ["full"] }
tokio-tungstenite = "0.17.1"
