[package]
name = "sse-bencher"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
eventsource-client = "0.10.1"
futures-util = "0.3.21"
rand = "0.8.5"
tokio = { version = "1.18.2", features = ["full"] }
