[package]
name = "sse-with-warp"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
futures-util = "0.3.21"
tokio = { version = "1.18.2", features = ["full"] }
tokio-stream = { version = "0.1.9", features = ["sync"] }
warp = "0.3.2"
