[package]
name = "with-tungstenite"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
futures-util = "0.3.21"
tokio = { version = "1.18.2", features = ["full"] }
tokio-tungstenite = "0.17.1"
