version: "3.9"
services:
  with-tungstenite:
    build: ./with-tungstenite
  bencher:
    build: ./bencher
    environment:
      - SERVER=with-tungstenite:8080
    depends_on:
      - with-tungstenite
    sysctls:
      - net.ipv4.ip_local_port_range=1024 60999
